name: Rust

on:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:

  build:

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04, windows-2019]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.1
    - name: install linux deps
      if: startsWith(matrix.os,'ubuntu')
      run: |
        sudo apt install libwebkit2gtk-4.0-dev libappindicator3-dev
    - name: Build Wikit CLI
      working-directory: ./cli
      run: |
        cargo build --release
    - name: Build Wikit Desktop
      working-directory: ./desktop
      run: |
          rustup target add wasm32-unknown-unknown
          cargo install tauri-cli trunk
          cargo tauri build

    - name: Prepare Linux Artifact
      if: startsWith(matrix.os,'ubuntu')
      run: |
        mkdir -p linux-artifact
        mv target/release/wikit linux-artifact
        mv target/release/bundle/appimage/wikit*.AppImage linux-artifact
    - name: Archive Linux Artifact
      if: startsWith(matrix.os,'ubuntu')
      uses: actions/upload-artifact@v2
      with:
        name: linux-artifact
        path: |
          linux-artifact

    - name: Prepare Darwin Artifact
      if: startsWith(matrix.os,'macos')
      run: |
        mkdir -p darwin-artifact
        mv target/release/wikit darwin-artifact
        mv target/release/bundle/dmg/*.dmg darwin-artifact
    - name: Archive Darwin Artifact
      if: startsWith(matrix.os, 'macos')
      uses: actions/upload-artifact@v2
      with:
        name: darwin-artifact
        path: |
          darwin-artifact

    - name: Prepare Windows Artifact
      if: startsWith(matrix.os,'windows')
      run: |
        mkdir windows-artifact
        move target\release\wikit.exe windows-artifact
        move target\release\bundle\msi\*.msi windows-artifact
    - name: Archive Windows Artifact
      if: startsWith(matrix.os, 'windows')
      uses: actions/upload-artifact@v2
      with:
        name: windows-artifact
        path: |
          windows-artifact
